spring:
  profiles:
    active: test

redis:
  host: 15.164.165.253
  port: 8080

logging:
  file:
    name: application-debug.log
    path: /logs
  pattern:
    file: "%d %-5level [%thread] &logger : %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 10
  level:
    root: info
    seeuthere.goodday: debug