spring:
  profiles:
    active: test
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          service-url: http://localhost:8080
logging:
  file:
    name: application-debug.log
    path: /logs
  pattern:
    file: "%d %-5level [%thread] &logger : %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 10
  level:
    root: info
    seeuthere.goodday: debug
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
management:
  metrics:
    export:
      cloudwatch:
        namespace:
        batch-size: 20
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

