spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:subway
    username: sa
    password:
  h2:
    console:
      enabled: true
handlebars:
  suffix: .html
  enabled: true
security:
  jwt:
    token:
      secret-key: my_secret_is_secret
      expire-length: 3600000