spring:
  config:
    activate:
      on-profile:
        - prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/seeyouthere?userSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  sql:
    init:
      mode: always
handlebars:
  suffix: .html
  enabled: true
url:
  kakao: https://seeyouthere.o-r.kr
