export const COLOR = {
  PRIMARY: '#2962FF',
  PRIMARY_DARK: '#0039CB',
  PRIMARY_LIGHT: '#768FFF',
  PRIMARY_BACKGROUND: '#F9FAFF',

  ERROR: '#FF4081',
  ERROR_LIGHT: '#FF79B0',

  BACKGROUND: '#fff',

  ON_PRIMARY: '#FFF',
  BORDER_INPUT: '#EEE',
  PLACEHOLDER: '#999',

  ICON: '#666',
  HEADING: '#555',
  PARAGRAPH: '#333',
};

export const LAYOUT = {
  NAV_HEIGHT: '3.5rem',
  NAV_RIGHT_WIDTH: '26rem',
  NAV_ICON_SIZE: '1.75rem',

  TABLET_WIDTH: '832px',

  MARGIN: '1.5rem',
};

export const Z_INDEX = {
  MAP: 0,
  CONTENT: 10,
  NAVBAR: 20,
  HAMBURGER_MENU: 30,
};
